version: '3.8'

services:
  # PostgreSQL сервис
  postgres:
    image: postgres:15-alpine
    container_name: exam_postgres
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: postgres_location
      POSTGRES_PASSWORD: 5513
    ports:
      - "5615:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/datad
    networks:
      - exam_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d comments_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: exam_redis
    ports:
      - "5616:6379"  
    #TODO Здесь нужно будет добавить сохранение на хосет даных
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    networks:
      - exam_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  exam_network:
    driver: bridge