version: '3.8'

services:
  # PostgreSQL сервис
  postgres:
    image: postgres:15-alpine
    container_name: comments_postgres
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5513
    volumes:
      - postgres_data:/var/lib/postgresql/datad
    networks:
      - comments_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d comments_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: comments_redis
    command: redis-server --save "" --appendonly no
    volumes:
      - redis_data:/data
    networks:
      - comments_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  comments:
    build: .
    command: ./server
    environment:
      - DATABASE_URL=postgres://postgres:5513@postgres:5432/comments_db?sslmode=disable
      - PORT=5001
    container_name: comments
    ports:
      - "5002:5001"
    networks:
      - comments_network
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  comments_network:
    driver: bridge